### ISSUE TITLE
Next JS 14 + Contentful Caching, Fetch tags, Revalidation & Webhooks

### ISSUE THREAD

**Issue by subhranshudas** [contentful/live-preview#652]
I was trying to follow few resources from Contentful - 

https://www.contentful.com/blog/integrate-contentful-next-js-app-router/
https://github.com/contentful/live-preview/blob/main/examples/next-app-router/app/api/revalidate/route.ts#L24

I am having **trouble understanding the best practices** for the **following scenario** in the above context.

I have `/blogs` and `/blogs/[slug]` pages in a simple Next 14 app. I am using `fetch` & `graphql` queries to get data from these
Now in the 
`/blogs` page i call `getAllPosts()` with` tags: ["posts"]`

`/blogs/[slug]` page i call `getPost(slug)` with` tags: ["posts"]`

For revalidation,
When i edit or create an entry in CF., i have setup contentful webhook with default payload. and a Next JS `/api/revalidate` 
inside which i am trying to revalidate using `revalidateTag(tag)` where i get the `tag` from the request payload 
```
const body = await request.json();
const contentType: string = body.sys.contentType.sys.id;
let tag;
if (contentType === "post") {
tag = "posts"
}
revalidateTag(tag)
```

**My doubt is** 

1. when i use `revalidateTag(tag)` it revalidates the "posts" data cache which means all the posts are revalidated even if i change 1 post entry?
2. was thinking to use `tags: [slug]` & `revalidateTag(slug)` approach, which will purge cache for 1 post and hence that specifc page, but how do i revalidate the "/blogs" page which has all the posts at the same time? how to handle this?

Also i read in the above article that we should go page specific
![Screenshot 2024-04-04 at 8 29 13 AM](https://github.com/contentful/live-preview/assets/6158624/e54191c6-7ead-4974-beac-39b7af1e9905)

In the code snippet in your example repo (above link) how are you handling revalidating the `"blogs"` tag??
![Screenshot 2024-04-04 at 8 40 13 AM](https://github.com/contentful/live-preview/assets/6158624/2b29c572-ee9d-4681-835f-244be89dacc7)
![Screenshot 2024-04-04 at 8 40 22 AM](https://github.com/contentful/live-preview/assets/6158624/d1818f58-ff23-46f2-bdc5-f91a1234a1b3)

In general if there are a large number of posts (300) how do i use the best practices here?

Thank you for reading my query.

**Comment by 2wce** [comment]
Hi @subhranshudas thank you for using Live Preview. Revalidation is a feature that's continuously being improved by Vercel but for the use case you are describing it might have limitations.

1. in theory you should be able to add multiple tags so that the `/blogs` endpoint has `['blogs']` and it also has an array of all slugs that are on that endpoint. That way if you revalidate a slug on a specific post it gets revalidated on the blogs endpoint as well. However working with multiple tags doesn't always work as [expected](https://github.com/vercel/next.js/issues/55960)
2. some of the limitations have now been highlighted in the [docs](https://nextjs.org/docs/app/api-reference/functions/revalidatePath) so you can also keep an eye out on that

In the end you might have to get a bit creative since there are no established patterns yet and if that doesn't work you can also reach out to Vercel & provide them with this feedback so they can try to include it in their next releases
